/**
 * prisma/seed.ts
 * Cria o superadmin Merlin no banco de dados.
 *
 * Run: npx prisma db seed
 * Requires: DATABASE_URL in .env.local
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore — types generated by `prisma generate`
import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

const ADMIN = {
  email: 'merlin@cyberportal.dev',
  password: 'CyberPortal@2025!', // ⚠️ Change before production
  name: 'Merlin',
  role: 'ADMIN' as const,
  targetRole: 'Security Engineer',
  studyHoursPerWeek: 20,
  location: 'Europe',
};

async function main() {
  console.log('🌱 Seeding database...\n');

  const existing = await prisma.user.findUnique({ where: { email: ADMIN.email } });

  if (existing) {
    console.log(`⚠️  User "${ADMIN.email}" already exists — skipping.`);
    console.log('   To reset: delete via Prisma Studio and re-run seed.\n');
    return;
  }

  // bcrypt rounds=12 (OWASP recommendation)
  const passwordHash = await bcrypt.hash(ADMIN.password, 12);

  const user = await prisma.user.create({
    data: {
      email: ADMIN.email,
      passwordHash,
      name: ADMIN.name,
      role: ADMIN.role,
      targetRole: ADMIN.targetRole,
      studyHoursPerWeek: ADMIN.studyHoursPerWeek,
      location: ADMIN.location,
      isActive: true,
    },
  });

  console.log('✅ Superadmin created successfully!');
  console.log(`   ID:    ${user.id}`);
  console.log(`   Email: ${user.email}`);
  console.log(`   Name:  ${user.name}`);
  console.log(`   Role:  ${user.role}`);
  console.log('\n🔑 Login credentials (change before production!):');
  console.log(`   Email:    ${ADMIN.email}`);
  console.log(`   Password: ${ADMIN.password}\n`);
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
