/**
 * lib/prisma.ts
 * Prisma Client singleton for Node.js runtime.
 *
 * NOTE: PrismaClient is only available after running:
 *   npx prisma generate
 *   npx prisma migrate dev
 *
 * The `@prisma/client` import resolves to `.prisma/client` after generation.
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore — types generated by `prisma generate`; safe to ignore pre-generation
import { PrismaClient } from '@prisma/client';

const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClient | undefined;
};

export const prisma: PrismaClient =
  globalForPrisma.prisma ??
  new PrismaClient({
    log: process.env.NODE_ENV === 'development' ? ['error', 'warn'] : ['error'],
  });

if (process.env.NODE_ENV !== 'production') {
  globalForPrisma.prisma = prisma;
}
