/**
 * lib/prisma.ts — Prisma 7 singleton
 *
 * Prisma 7 requires:
 * 1. provider = "prisma-client" in schema.prisma
 * 2. PrismaPg adapter passed to PrismaClient constructor
 * 3. Run `npx prisma generate` before starting the app
 *
 * Import from @prisma/client works when no custom output is set.
 */

// @ts-ignore — generated by `prisma generate` into node_modules/@prisma/client
import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';

const globalForPrisma = globalThis as unknown as {
  prisma: typeof prismaInstance | undefined;
};

function createClient() {
  const adapter = new PrismaPg({
    connectionString: process.env.DATABASE_URL!,
  });
  // @ts-ignore
  return new PrismaClient({ adapter });
}

const prismaInstance = createClient();

export const prisma = globalForPrisma.prisma ?? prismaInstance;

if (process.env.NODE_ENV !== 'production') {
  globalForPrisma.prisma = prisma;
}
