/**
 * lib/prisma.ts — Prisma 7 singleton
 * Requires `prisma generate` to be run first (done in postinstall/buildCommand)
 */

/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-expect-error — PrismaClient generated by `prisma generate`; types exist at runtime
import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';

const globalForPrisma = globalThis as unknown as {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  prisma: any | undefined;
};

function createClient() {
  const adapter = new PrismaPg({
    connectionString: process.env.DATABASE_URL!,
  });
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return new (PrismaClient as any)({ adapter });
}

export const prisma = globalForPrisma.prisma ?? createClient();

if (process.env.NODE_ENV !== 'production') {
  globalForPrisma.prisma = prisma;
}
